import React from 'react'

export default function Itemtwo() {
  return (
    <div className='Itemtwo'>
      <h1>Privacy Policy</h1>
      <p>At Amigos E-commerce Store, we are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy outlines how we collect, use, and safeguard your data when you interact with our website and services. We may collect information such as your name, contact details, payment information, and browsing behavior to process your orders, provide customer support, and enhance your shopping experience. Your data is kept confidential and is only shared with trusted third parties for essential purposes such as payment processing and order fulfillment. We use industry-standard security measures to protect your information and maintain its accuracy. By using our services, you consent to the practices described in this Privacy Policy, which may be updated periodically. If you have any questions or concerns about your privacy, please contact us at [Contact Information]. Your privacy matters to us, and we are dedicated to keeping your information secure and respecting your choices regarding its use.</p>
      <p>We retain your personal data for as long as necessary to fulfill the purposes outlined in this Privacy Policy, unless a longer retention period is required by law. You have the right to access, correct, or delete your personal information held by us. If you wish to exercise these rights or have any concerns about the data we hold, please contact us using the provided contact information. We may use cookies and similar tracking technologies to improve your online experience and gather information about your preferences. You can modify your browser settings to control the use of cookies, but this may limit certain features on our website. We respect "Do Not Track" signals, and if your browser sends one, we will honor it. We are committed to transparent data practices and strive to provide you with choices and control over your personal information while maintaining the highest standards of security and privacy.</p>
      <p>This Privacy Policy outlines how we collect, use, and safeguard your data when you interact with our website and services. We may collect information such as your name, contact details, payment information, and browsing behavior to process your orders, provide customer support, and enhance your shopping experience. Your data is kept confidential and is only shared with trusted third parties for essential purposes such as payment processing and order fulfillment. We use industry-standard security measures to protect your information and maintain its accuracy. By using our services, you consent to the practices described in this Privacy Policy, which may be updated periodically. If you have any questions or concerns about your privacy, please contact us at [Contact Information]. Your privacy matters to us, and we are dedicated to keeping your information secure and respecting your choices regarding its use.</p>
      <p>This Privacy Policy outlines how we collect, use, and safeguard your data when you interact with our website and services. We may collect information such as information and maintain its accuracy. By using our services, you consent to the practices described in this Privacy Policy, which may be updated periodically. If you have any questions or concerns about your privacy, please contact us at [Contact Information]. Your privacy matters to us, and we are dedicated to keeping your information secure and respecting your choices regarding its use.</p>
    </div>
  )
}
